server:
  port: ":8080"
  host: "http://localhost"
  rootEndpoint: "/api"
  statusEndpoint: "/status"
  shortenEndpoint: "/shorten"
  limitEndpoint: "/shorten/limit"
  findEndpoint: "/find"

database:
  type: "sqlite3"

shortUrl:
  length: 5
